-- CUSTOMER SERVICE CHAT v2
-- Jalankan di Supabase SQL Editor.
-- Jika tabel versi lama sudah ada, gunakan database/project baru
-- atau hapus tabel lama terlebih dahulu.

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  public_id varchar(20) unique not null,
  access_hash varchar(64) not null,
  display_name varchar(40) not null default 'Pelanggan',
  status varchar(10) not null default 'open'
    check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null
    references public.conversations(id) on delete cascade,
  sender_type varchar(10) not null
    check (sender_type in ('customer','admin')),
  message text not null
    check (char_length(message) between 1 and 2000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists conversations_updated_idx
on public.conversations(updated_at desc);

create index if not exists messages_conversation_idx
on public.messages(conversation_id, id);

create or replace function public.touch_conversation()
returns trigger
language plpgsql
as $$
begin
  update public.conversations
  set updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists messages_touch_conversation
on public.messages;

create trigger messages_touch_conversation
after insert on public.messages
for each row execute function public.touch_conversation();

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Tidak ada policy publik.
-- Browser tidak mengakses tabel secara langsung.
-- Server Next.js menggunakan service-role key.
